### ISSUE TITLE
Still being used?

### ISSUE THREAD

**Issue by sommmen** [hendrik-schulte/UnityEnhanced#2]
Hi hendrik,

I think i might use this code. I was wondering if you still use it aswell in any projects or if you have moved on ever since? since the last commit was 2 years ago.

Also DOTS/ECS seems upcomming.

**Comment by hendrik-schulte** [comment]
Hey sommmen,

Yes, I actually use that code still in a larger project and it performs just fine. The last commit is two months old, actually. Please feel free to use it. 
May I ask what you are planning?

**Comment by sommmen** [comment]
> 
> 
> Hey sommmen,
> 
> Yes, I actually use that code still in a larger project and it performs just fine. The last commit is two months old, actually. Please feel free to use it.
> May I ask what you are planning?

Ah i overlooked the last commit indeed.
Well i did not use the framework, but rather i take from it as an example. I'm a bit new to unity so doing things myself helps with understanding things, certainly architecturally wise. Im writing it so i can make a switch later on to use this completely or use dots/ecs.

The problem is this is all very 'designer oriented', but i am no designer, im a programmer so i rather write an algorithm to generate lets say a level for me than build it myself. This is is a bit of a personal constraint, but hey.

I'm making a personal project. I always liked the 'space' genre, and strategy / rts / simulation games. So i'm making a simple 2d economy game where you have to manage planets and resources. The idea is to later on use that code base to make a v2 where those resources are used to fund warfare.
